package viikko9;

// TÄSSÄ TIEDOSTOSSA DEMOTAAN, KUINKA LUODAAN INTERFACE
// YLEENSÄ INTERFACEA MYÖS KÄYTETÄÄN ELI ENGLANNIN SANA
// IMPLEMENTS JOSSAIN. TARKKAANOTTAEN JATKOKURSSEILLA TEILLÄ
// JAVA TAI OIKEASTAAN HILAVITKUTIN NIMELTÄÄN FRAMEWORK TEKEE
// INTERFACEN KÄYTTÄMISEN

// YHDESSÄ TIEDOSTOSSA LUODAANKIN INTERFACE EIKÄ SANA CLASS
public interface Viesti {
	// METODIN HEADERI PÄÄTETÄÄN PUOLIPISTEESEEN ELI TOTEUTUSTA
	// EI TÄSSÄ OLE
	public void lahetaViesti(String viesti);
	public String vastaanotaViestit();
}
